name: ReleaseCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh "tmpbkt1j" "folder1/VoiceAI.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "VoiceAI.zip"